version : '3'
services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/sicards.sql:/docker-entrypoint-initdb.d/1.sql"
  
  api:
    depends_on:
      - mysqldb
    build: ./api
    ports:
      - 8080:8080

  front:
    depends_on:
      - mysqldb
    build: ./front
    ports:
      - 80:80
