version : '3'
services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/simcards.sql:/docker-entrypoint-initdb.d/1.sql"
  
  api:
    depends_on:
      - mysqldb
    build: ./api
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/dust?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

  front:
    depends_on:
      - mysqldb
    build: ./front
    ports:
      - 80:80
